### ISSUE TITLE
Possible sync option

### ISSUE THREAD

**Issue by Zym3x** [Laharah/deluge-uTorrentImport#10]
(i do not know where suggestion section is so i post it here, thx)

Can you make deluge sync with utorrent every "X" seconds?
would basically be just clicking the button automaticly.

Make plugin find downloads with just downloading metadata and also import those
(This is the real reason i need this plugin. all my torrents get stuck on metadata)

Would be AWESOME if you could do this, tough i do not know if this is possible. As i am no expert in the magical, mystical art that you gods posses (coding).

**Comment by Laharah** [comment]
Thanks for the feedback! Sorry it took so long for me to see it and get back to you.

Unfortunately I don't think that I can make syncing happen safely. If both uTorrent and deluge are running at the same time on the same torrents, they can run into read/write conflicts pretty easily. It's recommended that you shut down uTorrent before you run the program to be sure. Syncing would be useful, but this plugin is mostly for migrating from uTorrent to deluge more permanently.
