### ISSUE TITLE
Problem with importing torrents if you've moved files in the uTorrent client.

### ISSUE THREAD

**Issue by Darkfire102** [Laharah/deluge-uTorrentImport#14]
Tried importing my uTorrent torrents over to Deluge and it does not recognize all the files that I've right clicked and moved manually to another directory in uTorrent. So instead of finding the correct path of where the files are, every file that was moved elsewhere in the uTorrent client when imported over to Deluge tries to re-download the whole entire file because it does not recognize the new file name and/or location.

**Comment by Laharah** [comment]
Can you tell me what is and what version of utorrent you are usi

**Comment by Laharah** [comment]
closing this for lack of info, feel free to re-post or re-open if you're still having problems.

**Comment by OrangeFlavored** [comment]
Same problem here, uTorrent 2.2.1 and Windows 10 64-bit.  Hundreds of torrents fail to move across properly.
