### ISSUE TITLE
uTorrent 2.2.1 resume file supported?

### ISSUE THREAD

**Issue by LossAngeles** [Laharah/deluge-uTorrentImport#19]
Good day, 

I'm trying to import a uTorrent 2.2.1 file and it's complaining that the file is a directory and not a file. Deluge client version is 1.3.15 running on Win 7. Python version is 2.7. Perhaps this older version of uTorrent is not supported?

Thanks and regards.
-Greg
![image](https://user-images.githubusercontent.com/354491/37116055-e141601a-2201-11e8-84fc-3104d714e6c9.png)

**Comment by Laharah** [comment]
2.2.1 is definitely supported. You can only get that error message if your OS reports that the path you typed in is not a file. You should open the path and double check. It may be possible that it's a symlink, or is the file missing?

**Comment by LossAngeles** [comment]
Thank you for replying. No symlinks, and permissions check out. I admit it's very odd behavior. I'm stumped. Note: Python automatically populates the directory / file info and I've verified it. I also created a folder off the root directory (c:\uTor_move) and that fails as well =(

![image](https://user-images.githubusercontent.com/354491/37160229-9520d398-22a4-11e8-9160-18bae5e772af.png)

**Comment by Laharah** [comment]
very strange. Are you running deluge in classic mode or in server-client mode?

**Comment by Laharah** [comment]
Okay, I think I might be able to reproduce these errors now that I've got all the library information. I'm seeing that a bunch of the torrents that didn't get renamed correctly have file rename failures for file existing. I'm not entirely sure why, but I can start to look into it. I'll update here when I have more.

**Comment by LossAngeles** [comment]
Hello, so sorry it took so long to get back to you. I'm pretty sure it's in classic mode. The daemon runs on a Linux box and I use the client side install on Win7 to manage my torrents.

![image](https://user-images.githubusercontent.com/354491/37353720-2caff9f4-269d-11e8-823a-94ccbfd3a4ac.png)

**Comment by Laharah** [comment]
Ah, I think I might know the problem. Is uTorrent installed on the server machine or on your windows machine?

**Comment by LossAngeles** [comment]
uTorrent is running on the Windows machine.

**Comment by Laharah** [comment]
Yeah, the plugin can only import from the same machine. Since you're trying to import the uTorrent data from your windows machine, the server has no way to access your resume data or any of your torrents. You would have to transfer everything over to the linux machine first, then use the plugin on the server. Or you would have to have the deluge server running on your windows machine instead of a remote location.

**Comment by LossAngeles** [comment]
Thanks for replying. That makes sense. I think I might try to fire up this uTorrent install on the linux box under WINE. If that works it will solve my issue with Windows drive mappings instead of URL on many of the torrent source files. Thanks for your help ; cheers =)
