### ISSUE TITLE
Inactive folders

### ISSUE THREAD

**Issue by molly78** [Laharah/deluge-uTorrentImport#20]
Since your script parses utorrent's data so well...

A bit of a side step:

Would it be possible to have your awesome python scripts output the list of active folders / files that are currently loaded in utorrent?

I know I have a ton of dead stuff sitting in my completed folder, but no easy way to manage it so it ends up just sitting there tying up space.

In a perfect world I'd like to point a script to my Completed folder and it would move all the non-active files into a different folder based on whats loaded in utorrent...

Just a thought - I can send cookies as bribes tho...

**Comment by Laharah** [comment]
Well, there's no good way to add that to the plugin that wouldn't clutter things up. But if you want I could write you a stand-alone script that does that so long as you're comfortable running a python script. Getting just a huge list of files that are all tied to torrents in uTorrent is fairly straight forward. Do you want the script to just output all the file paths? Do you want it to try and narrow things down to folders? If you're comfortable with the command line I could have it compare to a directory and give you a list of files that can be safely deleted.

**Comment by molly78** [comment]
Well look at you go!

I figured it would be a stand alone script. And would base folders work? Or if it’s just one file that file name?

I think it would make things easier than having all the sub folders and files mentioned. 

I’m comfortable running scripts and if it moved the non-active data into a subfolder for further processing that would rock!

Just to make sure it’s no longer needed :)

Big thanks for the fast reply.

**Comment by Laharah** [comment]
Alright, I took 20 min or so this afternoon and knocked out this script:

https://gist.github.com/Laharah/da1b4b51d68987fca8a1c70617b02344

### Instructions:
* Make sure you have [python 3.6 installed](https://conda.io/miniconda.html)

* download the file in the zip or copy and paste it into an empty `.py` file

* **Shutdown uTorrent.**

* Either open a command window and use the script like so: `python active_seperation.py "C:\path\to\download\folder"` or you can use simply place the script in your downloads folder and double click it.

* The script will try and find your uTorrent data and cross-reference the download folder and your uTorrent data. (If it dosen't, you'll have to use the command line `python active_seperation.py "C:\path\to\download\folder" "C:\path\to\resume.dat"` )

* It will give a list of files/folders that aren't referenced by uTorrent and will ask if you want to move them to a subfolder

* if you answer no, the script exits, answer yes and the inactive items will be moved into a folder called `unreferenced`

Let me know if you have any troubles running the script.

**Comment by molly78** [comment]
Wow - you seriously rock!

Running Win10 as a reference with uTorrent 3.4.5

I did have to specify the folders as it downloads to a network folder, but fortunately you can right click on the Anaconda Prompts menu bar to get the paste command. This let me copying the paths with windows to build the command in notepad first

Freed up almost 300gb of space and relaunched uTorrent with no missing files noted.

Buddy - you rock again!

**Comment by Laharah** [comment]
Glad to be of help!

**Comment by molly78** [comment]
Are you going to release this? I would and post it up on the forums / reddit

I’m sure I’m it the only one that would find it super handy!

Thx again

**Comment by Laharah** [comment]
Feel free to share it wherever, I'm just not wild about supporting it officially as I don't feel like making it more user friendly. It's simple enough in it's current form, and easy to use if you know how to install python and run a script. But it would take a good deal of work to make it portable, streamlined, and more feature rich.

**Comment by molly78** [comment]
Just curious. Also in my root utorrent folder there’s quite literally every torrent I have ever downloaded. Now it’s setup to move finished torrents to a different folder, but it wasn’t before as I didn’t realize it kept them

Any chance of working your amazing magicalness on this too?

Can it possibly move unreferenced torrents to a Finished folder too?

Once again you went over and above to even listen to my first request so huge thanks!
