### ISSUE TITLE
no web ui?

### ISSUE THREAD

**Issue by mgaulton** [Laharah/deluge-uTorrentImport#21]
Based on what I can see in the source, there should be a webui but i'm not getting anything in the UI after enabling the plugin. no errors in the logs that I can see. Not sure if it's a system them or a dev build thing.

Thanks.

I am on OpenSuse Leap 15
deluge 2.0.0b2.dev313
libtorrent: 1.1.7.0
Python: 2.7.14
OS: Linux

**Comment by Laharah** [comment]
sorry, no web UI. those are just stubs for the plugin template. I'm open to pull requests though :).

**Comment by mgaulton** [comment]
OK, i'll poke around at it. My GTK is broken so :( heh
Thanks!
