### ISSUE TITLE
Importing fields: date, uploaded, downloaded

### ISSUE THREAD

**Issue by ZimbiX** [Laharah/deluge-uTorrentImport#4]
I would rather like to be able to keep the following fields for each torrent:

- Date Added
- Uploaded
- Downloaded (for purposes of calculating the ratio)

Besides missing these, your plugin works brilliantly. Thanks for developing it =)

I wasn't sure if I should make a separate issue for each field.

**Comment by Laharah** [comment]
The single issue is fine :). I'll see what I can do about adding this info to the torrent. Deluge doesn't have any API for updating those fields, so I'll have to change the values directly. And while I can probably get them to show up right after adding, some of them may not persist after deluge reloads their state from libtorrent. It'll depend on whether deluge keeps those stats internally, or if libtorrent handles it. 

I'll look into it and see what I can do.

**Comment by Laharah** [comment]
well, some good news, but mostly bad.

The date added is do-able, but the ratio stats aren't. Libtorrent keeps track of those and there's no easy way to update them. I've come up with a workaround, but it's evil. It involves editing the fastresume data directly, re-encoding it, deleting the torrent from libtorrent and re-importing it under deluge's nose. If anything goes wrong while it happens, some seriously bad stuff can go wrong and get out of sync.

I'm not really comfortable mass releasing a plugin that can seriously harm peoples setups, so I'm not going to put in torrent-metadata importing. I'll leave this issue open encase I get some more demand for it or I come up with a safer way to do it.

**Comment by ZimbiX** [comment]
Huh, that does sound like a nasty workaround. The date's probably the most important, anyway.

**Comment by Laharah** [comment]
I've got a local branch that updates the date added serverside. I'll push it up once I've gotten a chance to add the GUI options and test it some more. 

I also want to take a look at importing labels too, but I wanna make sure that if I do, I support the lableplus plugin.

**Comment by ZimbiX** [comment]
Alrighty. I'd be keen to test that out =)

Cheers.

**Comment by Laharah** [comment]
The new release adds support for date preservation. Let me know if you find any bugs!
