### ISSUE TITLE
Failed to get resume.dat

### ISSUE THREAD

**Issue by Wolfeman0101** [Laharah/deluge-uTorrentImport#8]
Everything on Deluge seems to be working but I'm getting this error.

Failed to get resume.dat. Reason: [Errno 2] No such file or directory: 'C:\\Users\\Bryan\\AppData\\Roaming\\uTorrent'

Going from Windows 10 to Deluge in FreeNAS.

**Comment by Laharah** [comment]
it seems that you don't have utorrent installed on the system you're running the importer on. Either that or it's not in it's default location. can you find the resume.dat file at that path? If you know where it is you can enter the path manually. 

Can you explain a bit more about your setup? Is deluge installed on the same system that utorrent was on?

**Comment by Wolfeman0101** [comment]
Yeah I installed Deluge on FreeNAS and uTorrent is on my Windows box.  Yeah the resume.dat file is in that location.

**Comment by Laharah** [comment]
The import plugin relies on both deluge and utorrent being installed on the same system. It needs to be able to follow the correct paths to the torrent files and their downloaded files. If you transfer your uTorrent installation to freenas first, making sure everything seeds correctly, the plugin may then be able to import correctly
